In [416]:
import tensorflow.keras as keras
import numpy as np
from sklearn.utils import resample
import pandas as pd
import pickle
import os
import csv
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.linear_model import LogisticRegression
from statistics import mean
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import SGD
from keras.regularizers import l2
MODEL_PATH = './model/'
DATA_PATH = './data/'

In [387]:
data = pd.read_csv('data/adult.data', na_values=["?"])
target_dataset = pd.DataFrame(data.iloc[1:10001,].values)
shadow_dataset = pd.DataFrame(data.iloc[15001:30001,].values)
attack_test_nonmembers = pd.DataFrame(data.iloc[11001:14001,].values)
attack_test_members = pd.DataFrame(data.iloc[2001:5001,].values)

In [417]:
data = pd.read_csv('data/adult.data', na_values=["?"], header=None)
data.dropna(inplace=True)
target_dataset = data.sample(n = 10000, replace = False)
df_rest = data.loc[~data.index.isin(target_dataset.index)]
shadow_dataset = df_rest.sample(n = 12000, replace = False)
df_rest = df_rest.loc[~df_rest.index.isin(shadow_dataset.index)]
attack_test_nonmembers = df_rest.sample(n = 5000, replace = False)
attack_test_members =  target_dataset.iloc[:7000,:].sample(n = 5000, replace = False)

In [ ]:
target_dataset = pd.read_csv('data/adult_sds.csv', na_values=["?"])
shadow_dataset = pd.read_csv('data/adultODS10K_to_25K.csv', na_values=["?"])
attack_test_nonmembers = pd.read_csv('data/adultODS25K_to_28K.csv', na_values=["?"])
attack_test_members = pd.read_csv('data/adultODS1_to_3K.csv', na_values=["?"])

In [418]:
def read_data(data_name):
    with np.load(DATA_PATH + data_name) as f:
        train_x, train_y, test_x, test_y = [f['arr_%d' % i] for i in range(len(f.files))]
    return train_x, train_y, test_x, test_y

In [419]:
def old_transform_data(dataset):
    x = dataset.iloc[:,0:dataset.shape[1]-1] # seperate the feature column from class label
    y = dataset.iloc[:,-1] # label column
    

    dim=x.shape[1] # number of feature columns

    #num of classes
    num_classes=2

    for j in range(0,dim):
        if x.iloc[:,j].dtypes == object:   # transform categorical variables
            x.iloc[:,j] = x.iloc[:,j].astype('category') # change datatype to categorical
            x.iloc[:,j] = x.iloc[:,j].cat.codes # change from category name to category number
        else:  #transform numrical variables to standard scaler form 
            sc = StandardScaler()  
            val=np.array(x.iloc[:,j]).reshape(-1,1)
            std_data = sc.fit_transform(val)
            std_data = pd.DataFrame(std_data)
            x.iloc[:,j]=std_data
            print(x.iloc[:,j])

    y = y.astype('category') # change label to categorical
    y = y.cat.codes # change from category name to number

    x=np.array(x)
    y=np.array(y)
    
    
    y=to_categorical(y)
    
    return x, y, dim

In [420]:
def transform_data(dataset):
    
    for col in [1,3,5,6,7,8,9,13,14]:
        le = LabelEncoder()
        dataset[col] = le.fit_transform(dataset[col].astype('str'))
    
    # normalize the values
    x_range = [i for i in range(14)]
    dataset[x_range] = dataset[x_range]/dataset[x_range].max()

    x = dataset[x_range].values
    y = dataset[14].values
    
    dim = x.shape[1]
    
    x=np.array(x)
    y=np.array(y)
    
    
    y=to_categorical(y)
    
    return x, y, dim

In [421]:
def load_target_data(dataset, test_ratio):
    x, y, dim = transform_data(dataset)
    
    #trainX,testX, trainY, testY = train_test_split(x, y, test_size=test_ratio, random_state=0, stratify=y)
    trainX = x[0:7000,]
    testX = x[7000:,]
    trainY = y[0:7000,]
    testY = y[7000:,]
    return (trainX, trainY), (testX, testY), dim

In [422]:
def build_simple_mlp(n_class,pix,d):

    model = Sequential()
    model.add(Dense(256, input_dim=pix))
    model.add(Activation("relu"))
    #model.add(Dropout(0.01))
    
    model.add(Dense(256, kernel_regularizer=l2(0.01)))
    model.add(Activation("relu"))
    #model.add(Dropout(0.01))
    
    
    #model.add(Dense(248))
    #model.add(Activation("relu"))
    #model.add(Dropout(0.01))

    model.add(Dense(64))
    model.add(Activation("relu"))
    model.add(Dropout(0.01))
    
    model.add(Dense(n_class, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    act_layer=3
    
    return model, act_layer

In [423]:
def load_shadow_data(dataset, n_shadow, shadow_size, test_ratio):
    x, y, _ = transform_data(dataset)
    
    shadow_indices = np.arange(len(dataset))
    
   
    for i in range(n_shadow):
        shadow_i_indices = np.random.choice(shadow_indices, shadow_size, replace=False)
        shadow_i_x, shadow_i_y = x[shadow_i_indices], y[shadow_i_indices]
        trainX,testX, trainY, testY = train_test_split(shadow_i_x, shadow_i_y, test_size=test_ratio)
        print('shadow_i_trainX = ', len(trainX), 'shadow_i_trainY = ', len(trainY), 'shadow_i_testX = ', len(testX), 'shadow_i_testY = ', len(testY))
        
        np.savez(DATA_PATH + 'shadow_adult{}_data.npz'.format(i), trainX, trainY, testX, testY)

In [424]:
def train_shadow_models(n_shadow, n_class, dim, channel):
    full_sm_train_pred=[]
    full_sm_train_class=[]
    
    full_sm_test_pred=[]
    full_sm_test_class=[]
    
    full_clz_train=[]
    full_clz_test=[]
    
    members=[]
    nonmembers=[]

    for j in range(n_shadow):
        
        print("Shadow Model ", j)
        
        print('Training shadow model {}'.format(j))
        data = read_data('shadow_adult{}_data.npz'.format(j))
        x_shadow_train, y_shadow_train, x_shadow_test, y_shadow_test = data
        #print('x_shadow trian\n', x_shadow_train,'\n y_shadow trian\n', y_shadow_train, '\n x_shadow test\n', x_shadow_test, '\n y_shadow test\n', y_shadow_test)

        model, act_layer = build_simple_mlp(n_class,dim, channel)
            
            
        # fit model
        history = model.fit(x_shadow_train, y_shadow_train, epochs=EPS, batch_size=32, validation_data=(x_shadow_test, y_shadow_test), verbose=0)
    
        # evaluate model
        _, train_acc = model.evaluate(x_shadow_train, y_shadow_train, verbose=0)
        _, test_acc = model.evaluate(x_shadow_test, y_shadow_test, verbose=0)
        print("Shadow Train acc : ", (train_acc * 100.0),"Shadow Test acc : ", (test_acc * 100.0))

    
        #train SM
        sm_train_pred=model.predict(x_shadow_train, batch_size=32)
        sm_train_class=np.argmax(y_shadow_train,axis=1)
    
    
        #test SM
        sm_test_pred=model.predict(x_shadow_test, batch_size=32)
        sm_test_class=np.argmax(y_shadow_test,axis=1)
        
     
        full_sm_train_pred.append(sm_train_pred)        
        full_sm_train_class.append(sm_train_class)
        members.append(np.ones(len(sm_train_pred)))
        
        full_sm_test_pred.append(sm_test_pred)        
        full_sm_test_class.append(sm_test_class) 
        nonmembers.append(np.zeros(len(sm_test_pred)))


    full_sm_train_pred = np.vstack(full_sm_train_pred)
    full_sm_train_class = [item for sublist in full_sm_train_class for item in sublist]
    members = [item for sublist in members for item in sublist]
    
    full_sm_test_pred = np.vstack(full_sm_test_pred)
    full_sm_test_class = [item for sublist in full_sm_test_class for item in sublist]
    nonmembers = [item for sublist in nonmembers for item in sublist]
    
    shadow_train_performance=(full_sm_train_pred, np.array(full_sm_train_class))
    shadow_test_performance=(full_sm_test_pred, np.array(full_sm_test_class))


    ###atack data preparation
    attack_x = (full_sm_train_pred,full_sm_test_pred)
    #attack_x = np.vstack(attack_x)
    
    attack_y = (np.array(members).astype('int32'),np.array(nonmembers).astype('int32'))
    #attack_y = np.concatenate(attack_y)
    #attack_y = attack_y.astype('int32')
    
    
    classes = (np.array(full_sm_train_class),np.array(full_sm_test_class))
    #classes = np.array([item for sublist in classes for item in sublist])


    attack_dataset = (attack_x,attack_y,classes)

            
    return  shadow_train_performance, shadow_test_performance, attack_dataset, x_shadow_train, y_shadow_train, x_shadow_test, y_shadow_test, model

In [425]:
def define_attack_model(n_class):
    model = Sequential()
    
    model.add(Dense(1))
    model.add(Activation("relu"))
    
    model.add(Dense(1))
    model.add(Activation("relu"))

    model.add(Dense(n_class, activation='softmax'))

    # compile model
    opt = SGD(learning_rate=0.0001, momentum=0.9)
    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

In [426]:
def attack_mlp(pix,d):

    model = Sequential()
    model.add(Dense(64, input_dim=pix))
    model.add(Activation("relu"))
    #model.add(Dropout(0.1))

#     model.add(Dense(32))
#     model.add(Activation("tanh"))
#     model.add(Dropout(0.01))
    
    model.add(Dense(2, activation='softmax'))
    model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    act_layer=1
    
    return model, act_layer

In [427]:
def prep_attack_data(n_attack_data):

    attack_mem = pd.DataFrame(n_attack_data[0][0])
    attack_nmem = pd.DataFrame(n_attack_data[0][1])
    
    attack_mem_status = pd.DataFrame(n_attack_data[1][0])
    attack_mem_status.columns = ["membership"]
    
    attack_nmem_status = pd.DataFrame(n_attack_data[1][1])
    attack_nmem_status.columns = ["membership"]
    
    real_class_mem = pd.DataFrame(n_attack_data[2][0])
    real_class_mem.columns = ["y"]
    
    real_class_nmem = pd.DataFrame(n_attack_data[2][1])
    real_class_nmem.columns = ["y"]

    memdf = pd.concat([attack_mem,attack_nmem],axis=0)
    memdf = memdf.reset_index(drop=True)

    memstatus =  pd.concat([attack_mem_status,attack_nmem_status],axis=0)
    memstatus = memstatus.reset_index(drop=True)

    realclass = pd.concat([real_class_mem,real_class_nmem],axis=0)
    realclass = realclass.reset_index(drop=True)

    attack_df = pd.concat([memdf,realclass,memstatus],axis=1)
    
    return attack_df

In [428]:
def prep_validation_data(attack_test_data):

    attack_mem = pd.DataFrame(attack_test_data[0][0])
    attack_nmem = pd.DataFrame(attack_test_data[0][1])
    
    attack_mem_status = pd.DataFrame(attack_test_data[1][0])
    attack_mem_status.columns = ["membership"]
    
    attack_nmem_status = pd.DataFrame(attack_test_data[1][1])
    attack_nmem_status.columns = ["membership"]
    
    real_class_mem = pd.DataFrame(attack_test_data[2][0])
    real_class_mem.columns = ["y"]
    
    real_class_nmem = pd.DataFrame(attack_test_data[2][1])
    real_class_nmem.columns = ["y"]
    
    mem_df = pd.concat([attack_mem,real_class_mem],axis=1)
    nmem_df = pd.concat([attack_nmem,real_class_nmem],axis=1)

#     memdf = pd.concat([attack_mem,attack_nmem],axis=0)
#     memdf = memdf.reset_index(drop=True)

#     memstatus =  pd.concat([attack_mem_status,attack_nmem_status],axis=0)
#     memstatus = memstatus.reset_index(drop=True)

#     realclass = pd.concat([real_class_mem,real_class_nmem],axis=0)
#     realclass = realclass.reset_index(drop=True)

#     attack_df = pd.concat([memdf,realclass,memstatus],axis=1)
    
    return mem_df, nmem_df

In [429]:
def load_attack_test_data(members, nonmembers):
    memberX, memberY, _ = transform_data(members)
    
    nonmemberX, nonmemberY, _ = transform_data(nonmembers)
    
    return memberX, memberY, nonmemberX, nonmemberY

In [430]:
def prety_print_result(mem, pred):
    tn, fp, fn, tp = confusion_matrix(mem, pred).ravel()
    print('TP: %d     FP: %d     FN: %d     TN: %d' % (tp, fp, fn, tn))
    if tp == fp == 0:
        print('PPV: 0\nAdvantage: 0')
    else:
        print('PPV: %.4f\nAdvantage: %.4f' % (tp / (tp + fp), tp / (tp + fn) - fp / (tn + fp)))

    return tp, fp, fn, tn, (tp / (tp + fp)), (tp / (tp + fn) - fp / (tn + fp)), ((tp+tn)/(tp+tn+fp+fn)),  (tp / (tp + fn))

In [431]:
def train_attack_model(attack_data, check_membership, n_hidden=50, learning_rate=0.01, batch_size=200, epochs=50, model='nn', l2_ratio=1e-7):

    x, y,  classes = attack_data

    train_x = x[0]
    train_y = y[0]
    test_x = x[1]
    test_y = y[1]
    train_classes = classes[0]
    test_classes = classes[1]
    
    
    checkmem_prediction_vals, checkmem_membership_status, checkmem_class_status = check_membership
    
    checkmem_prediction_vals=np.vstack(checkmem_prediction_vals)
    checkmem_membership_status=np.array([item for sublist in checkmem_membership_status for item in sublist])
    checkmem_class_status=np.array([item for sublist in checkmem_class_status for item in sublist])
    
    train_indices = np.arange(len(train_x))
    test_indices = np.arange(len(test_x))
    unique_classes = np.unique(train_classes)


    predicted_membership, target_membership = [], []
    for c in unique_classes:
        print("Class : ", c)
        c_train_indices = train_indices[train_classes == c]
        c_train_x, c_train_y = train_x[c_train_indices], train_y[c_train_indices]
        c_test_indices = test_indices[test_classes == c]
        c_test_x, c_test_y = test_x[c_test_indices], test_y[c_test_indices]
        c_dataset = (c_train_x, c_train_y, c_test_x, c_test_y)        
        
        full_cx_data=(c_train_x,c_test_x)
        full_cx_data = np.vstack(full_cx_data)

        full_cy_data=(c_train_y,c_test_y)
        full_cy_data = np.array([item for sublist in full_cy_data for item in sublist])
        
        d=1
        pix = full_cx_data.shape[1]
        classifier, _ = attack_mlp(pix,d)
        history = classifier.fit(full_cx_data, full_cy_data, epochs=EPS, batch_size=32, verbose=0)

        #get predictions on real train and test data
        c_indices = np.where(checkmem_class_status==c)
        pred_y = classifier.predict(checkmem_prediction_vals[c_indices])
        print(pred_y)
        c_pred_y = np.argmax(pred_y, axis=1)
        c_target_y = checkmem_membership_status[c_indices]
        
       
        target_membership.append(c_target_y)
        predicted_membership.append(c_pred_y)

    target_membership=np.array([item for sublist in target_membership for item in sublist])
    predicted_membership=np.array([item for sublist in predicted_membership for item in sublist])


    tp, fp, fn, tn, precision, advj, acc, recall = prety_print_result (target_membership,predicted_membership)   
    return tp, fp, fn, tn, precision, advj, acc, recall

In [432]:
def shokri_attack(attack_df, mem_validation, nmem_validation):
    
    predicted_membership, predicted_nmembership, true_membership, TP_idx, TN_idx  = [], [], [], [], []

    class_val = np.unique(attack_df['y'])
    ncval=attack_df.shape[1]-1
    
    for c_val in class_val:

        print(c_val)
        
        filter_rec_all = attack_df[(attack_df['y'] == c_val)]
        filter_rec_idx = np.array(filter_rec_all.index)
        
        attack_feat = filter_rec_all.iloc[:, 0:ncval]
        attack_class = filter_rec_all['membership']
             
        d=1
        pix = attack_feat.shape[1]
        
        attack_model, _ = attack_mlp(pix,d)
        
       
        history = attack_model.fit(attack_feat, attack_class, epochs=EPS, batch_size=32, verbose=0)
        
        mcval=mem_validation.shape[1]-1
        
        
        check_mem_feat = mem_validation[mem_validation['y']==c_val]
        check_nmem_feat = nmem_validation[nmem_validation['y']==c_val]
        
        if (len(check_mem_feat)!=0) and (len(check_nmem_feat)!=0):
        
            check_mem_feat_idx =  np.array(check_mem_feat.index)


            check_nmem_feat_idx =  np.array(check_nmem_feat.index)

            #print(check_nmem_feat_idx)
            #print(np.argmax(mpred,axis=1)==0)


            mpred = attack_model.predict(np.array(check_mem_feat))    
            predicted_membership.append(np.argmax(mpred,axis=1) )

            nmpred = attack_model.predict(np.array(check_nmem_feat))    
            predicted_nmembership.append(np.argmax(nmpred,axis=1) )        



            TP_idx.append(check_mem_feat_idx[np.where(np.argmax(mpred,axis=1)==1)[0]])

            TN_idx.append(check_nmem_feat_idx[np.where(np.argmax(nmpred,axis=1)==0)[0]])

    pred_members = np.array([item for sublist in predicted_membership for item in sublist])
    pred_nonmembers = np.array([item for sublist in predicted_nmembership for item in sublist])
    
    TP_idx_list = np.array([item for sublist in TP_idx for item in sublist])
    TN_idx_list = np.array([item for sublist in TN_idx for item in sublist])
    
    members=np.array(list(pred_members))
    nonmembers=np.array(list(pred_nonmembers))
    
    pred_membership = np.concatenate([members,nonmembers])
    ori_membership = np.concatenate([np.ones(len(members)), np.zeros(len(nonmembers))])
    
    return pred_membership, ori_membership, TP_idx_list, TN_idx_list

In [433]:
# trian target model
per_class_sample=5000
channel=0   
EPS=200
act_layer=3
n_class = 2
VERBOSE = 0
test_ratio = 0.3

(target_trainX, target_trainY), (target_testX, target_testY), dim = load_target_data(target_dataset, test_ratio)
target_model,_ = build_simple_mlp(n_class,dim, channel)
#get_trained_keras_models(model, (target_trainX, target_trainY), (target_testX, target_testY), num_models=1)
history = target_model.fit(target_trainX, target_trainY, epochs=EPS, batch_size=32, verbose=VERBOSE)
score = target_model.evaluate(target_testX, target_testY, verbose=VERBOSE)
print('\n', 'Model test accuracy:', score[1])


 Model test accuracy: 0.840666651725769


In [434]:
# prepare attack test data

members = []
nonmembers = []

memberX, memberY, nonmemberX, nonmemberY = load_attack_test_data(attack_test_members, attack_test_nonmembers)

# member
target_model_member_pred = target_model.predict(memberX, batch_size=32)
target_model_member_class = np.argmax(memberY, axis=1)
target_model_member_pred = np.vstack(target_model_member_pred)
#target_model_member_class = [item for sublist in target_model_member_class for item in sublist]
members.append(np.ones(len(target_model_member_pred)))
members = [item for sublist in members for item in sublist]


# nonmember
target_model_nonmember_pred = target_model.predict(nonmemberX, batch_size=32)
target_model_nonmember_class = np.argmax(nonmemberY, axis=1)
target_model_nonmember_pred = np.vstack(target_model_nonmember_pred)
#target_model_nonmember_class = [item for sublist in target_model_nonmember_class for item in sublist]
nonmembers.append(np.zeros(len(target_model_nonmember_pred)))
nonmembers = [item for sublist in nonmembers for item in sublist]

full_attack_test_pred_val = (target_model_member_pred, target_model_nonmember_pred)
full_attack_test_mem_status = (np.array(members).astype('int32'),np.array(nonmembers).astype('int32'))
full_attack_test_class_status = (np.array(target_model_member_class),np.array(target_model_nonmember_class))

print('\n pred', full_attack_test_pred_val)
print('\n class', full_attack_test_class_status)
print('\n mem status', full_attack_test_mem_status)

attack_test_data = (full_attack_test_pred_val, full_attack_test_mem_status,full_attack_test_class_status)

157/157 [==============================] - 0s 2ms/step

 pred (array([[9.9986386e-01, 1.3606111e-04],
       [9.9997908e-01, 2.0879399e-05],
       [2.3124990e-01, 7.6875007e-01],
       ...,
       [4.2168081e-01, 5.7831919e-01],
       [9.9958807e-01, 4.1195491e-04],
       [9.9999887e-01, 1.0409306e-06]], dtype=float32), array([[0.99833614, 0.00166391],
       [0.33577356, 0.66422635],
       [0.9685055 , 0.03149452],
       ...,
       [0.70970327, 0.29029676],
       [0.9149672 , 0.08503288],
       [0.9914294 , 0.00857064]], dtype=float32))

 class (array([0, 0, 0, ..., 1, 0, 0]), array([0, 1, 0, ..., 0, 0, 0]))

 mem status (array([1, 1, 1, ..., 1, 1, 1], dtype=int32), array([0, 0, 0, ..., 0, 0, 0], dtype=int32))


In [435]:
# save attack test dataset to csv
df = pd.DataFrame()
mem = pd.Series(full_attack_test_pred_val[0][:,0])
nonmem = pd.Series(full_attack_test_pred_val[1][:,0])
total = pd.concat([mem, nonmem],axis=0, ignore_index=True)
len(total)
df['prob_class_0'] = total
df = df.reset_index()
mem = pd.Series(full_attack_test_pred_val[0][:,1])
nonmem = pd.Series(full_attack_test_pred_val[1][:,1])
total = pd.concat([mem, nonmem],axis=0, ignore_index=True)
df['prob_class 1'] = total

mem = pd.Series(full_attack_test_mem_status[0][:])
nonmem = pd.Series(full_attack_test_mem_status[1][:])
total = pd.concat([mem, nonmem],axis=0, ignore_index=True)
df['mem_status'] = total

mem = pd.Series(full_attack_test_class_status[0][:])
nonmem = pd.Series(full_attack_test_class_status[1][:])
total = pd.concat([mem, nonmem],axis=0, ignore_index=True)
df['class_status'] = total

df.drop("index", axis=1, inplace=True)


df.to_csv('attack_test_data.csv')

In [436]:
#prepare shadow dataset
n_shadow_models = 20
shadow_data_size = 5000
test_ratio = 0.3

load_shadow_data(shadow_dataset, n_shadow_models, shadow_data_size, test_ratio)

shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_testX =  1500 shadow_i_testY =  1500
shadow_i_trainX =  3500 shadow_i_trainY =  3500 shadow_i_tes

In [437]:
#train shadow model
per_class_sample=5000
channel=0   
EPS=200
act_layer=3
n_class = 2
VERBOSE = 0
test_ratio = 0.3

n_shadow_train_performance, n_shadow_test_performance, n_attack_data, x_shadow_train, y_shadow_train, x_shadow_test, y_shadow_test, shadow_model_init = train_shadow_models(n_shadow_models, n_class, dim, channel)

Shadow Model  0
Training shadow model 0
Shadow Train acc :  89.99999761581421 Shadow Test acc :  84.46666598320007
47/47 [==============================] - 0s 1ms/step
Shadow Model  1
Training shadow model 1
Shadow Train acc :  88.88571262359619 Shadow Test acc :  83.60000252723694
47/47 [==============================] - 0s 1ms/step
Shadow Model  2
Training shadow model 2
Shadow Train acc :  90.34285545349121 Shadow Test acc :  82.99999833106995
47/47 [==============================] - 0s 2ms/step
Shadow Model  3
Training shadow model 3
Shadow Train acc :  88.17142844200134 Shadow Test acc :  82.13333487510681
47/47 [==============================] - 0s 1ms/step
Shadow Model  4
Training shadow model 4
Shadow Train acc :  90.2571439743042 Shadow Test acc :  83.33333134651184
47/47 [==============================] - 0s 1ms/step
Shadow Model  5
Training shadow model 5
Shadow Train acc :  89.7428572177887 Shadow Test acc :  82.40000009536743
47/47 [==============================] - 0s 1ms

In [438]:
n_attack_data

((array([[3.8187438e-01, 6.1812568e-01],
         [9.7239673e-01, 2.7603187e-02],
         [4.6574762e-01, 5.3425235e-01],
         ...,
         [9.9999976e-01, 2.9060186e-07],
         [9.9992776e-01, 7.2289426e-05],
         [1.3614281e-01, 8.6385721e-01]], dtype=float32),
  array([[1.7935550e-01, 8.2064456e-01],
         [9.9998313e-01, 1.6831158e-05],
         [1.2823899e-01, 8.7176102e-01],
         ...,
         [1.1326178e-01, 8.8673818e-01],
         [4.1509447e-01, 5.8490551e-01],
         [9.9922812e-01, 7.7187520e-04]], dtype=float32)),
 (array([1, 1, 1, ..., 1, 1, 1], dtype=int32),
  array([0, 0, 0, ..., 0, 0, 0], dtype=int32)),
 (array([1, 0, 1, ..., 0, 0, 1]), array([1, 0, 1, ..., 1, 1, 0])))

In [439]:
attack_df = prep_attack_data(n_attack_data)
attack_df

0         1  y  membership
0      0.381874  0.618126  1           1
1      0.972397  0.027603  0           1
2      0.465748  0.534252  1           1
3      0.871952  0.128048  0           1
4      0.350740  0.649260  1           1
...         ...       ... ..         ...
99995  0.999985  0.000015  0           0
99996  0.997915  0.002085  0           0
99997  0.113262  0.886738  1           0
99998  0.415094  0.584906  1           0
99999  0.999228  0.000772  0           0

[100000 rows x 4 columns]

In [440]:
mem_validation, nmem_validation = prep_validation_data(attack_test_data)
nmem_validation

0         1  y
0     0.998336  0.001664  0
1     0.335774  0.664226  1
2     0.968506  0.031495  0
3     0.005760  0.994240  0
4     0.716497  0.283503  0
...        ...       ... ..
4995  0.987254  0.012746  0
4996  0.520258  0.479742  0
4997  0.709703  0.290297  0
4998  0.914967  0.085033  0
4999  0.991429  0.008571  0

[5000 rows x 3 columns]

In [443]:
tp, fp, fn, tn, precision, advj, acc, recall = train_attack_model(n_attack_data, attack_test_data)

Class :  0
237/237 [==============================] - 0s 1ms/step
[[0.2934423  0.70655763]
 [0.29352674 0.7064733 ]
 [0.4228407  0.5771593 ]
 ...
 [0.29022825 0.70977175]
 [0.28037447 0.7196255 ]
 [0.2873     0.71270007]]
Class :  1
76/76 [==============================] - 0s 1ms/step
[[0.2828035  0.7171965 ]
 [0.31496772 0.6850323 ]
 [0.2962644  0.7037356 ]
 ...
 [0.28893104 0.7110689 ]
 [0.269594   0.730406  ]
 [0.28169298 0.718307  ]]
TP: 4963     FP: 4834     FN: 37     TN: 166
PPV: 0.5066
Advantage: 0.0258


In [441]:
pred_membership, ori_membership, TP_idx_list, TN_idx_list = shokri_attack(attack_df, mem_validation, nmem_validation)

0
119/119 [==============================] - 0s 1ms/step
1
38/38 [==============================] - 0s 1ms/step


In [442]:
tp, fp, fn, tn, precision, advj, acc, recall = prety_print_result (ori_membership,pred_membership)

TP: 4963     FP: 4830     FN: 37     TN: 170
PPV: 0.5068
Advantage: 0.0266


In [282]:
#save the prepared attack data on disk
np.savez(DATA_PATH + 'attack_purchase_data.npz', n_attack_data, x_shadow_train, y_shadow_train, x_shadow_test, y_shadow_test, shadow_model_init)

/home/msnkhan/anaconda3/envs/r4-base/lib/python3.7/site-packages/numpy/lib/npyio.py:719: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  val = np.asanyarray(val)


INFO:tensorflow:Assets written to: ram://a9382bc7-fd48-42a6-8436-af2bd2196281/assets


In [ ]:
# read stored attack model training data 
data_name = 'attack_adult_data.npz'
with np.load(DATA_PATH + data_name, allow_pickle=True) as f:
        n_attack_data, x_shadow_train, y_shadow_train, x_shadow_test, y_shadow_test, shadow_model_init = [f['arr_%d' % i] for i in range(len(f.files))]

In [283]:
tp, fp, fn, tn, precision, advj, acc, recall, target_membership, predicted_membership = train_attack_model(n_attack_data, attack_test_data)
#target_membership, predicted_membership = train_attack_model(n_attack_data, attack_test_data)

Class :  0
5/5 [==============================] - 0s 2ms/step
[[0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 0.49993768]
 [0.50006235 

4/4 [==============================] - 0s 2ms/step
[[0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.49783623 0.5021638 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.49819902 0.50180095]
 [0.49803716 0.5019628 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.4978264  0.5021736 ]
 [0.49785376 0.5021462 ]
 [0.4978264  0.5021736 ]

6/6 [==============================] - 0s 2ms/step
[[0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]
 [0.5003825  0.49961737]

7/7 [==============================] - 0s 1ms/step
[[0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]
 [0.49988297 0.500117  ]

6/6 [==============================] - 0s 2ms/step
[[0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]
 [0.4999905  0.50000954]

6/6 [==============================] - 0s 3ms/step
[[0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]
 [0.4997513  0.5002487 ]

8/8 [==============================] - 0s 1ms/step
[[0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]
 [0.5000827  0.49991733]

16/16 [==============================] - 0s 1ms/step
[[0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633 ]
 [0.49983662 0.5001633

10/10 [==============================] - 0s 1ms/step
[[0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064 ]
 [0.49959368 0.5004064

19/19 [==============================] - 0s 1ms/step
[[0.47552106 0.524479  ]
 [0.47475466 0.52524525]
 [0.4747141  0.52528584]
 ...
 [0.509445   0.49055496]
 [0.4809081  0.5190919 ]
 [0.47446224 0.5255377 ]]
Class :  19
8/8 [==============================] - 0s 1ms/step
[[0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0.50017816 0.49982172]
 [0

7/7 [==============================] - 0s 1ms/step
[[0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]
 [0.49997228 0.5000277 ]

4/4 [==============================] - 0s 2ms/step
[[0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]
 [0.49989274 0.50010717]

2/2 [==============================] - 0s 2ms/step
[[0.46655494 0.5334451 ]
 [0.4665675  0.5334326 ]
 [0.466556   0.533444  ]
 [0.46655127 0.5334488 ]
 [0.46672264 0.5332774 ]
 [0.46658096 0.5334191 ]
 [0.46655348 0.5334465 ]
 [0.4666728  0.53332716]
 [0.46656746 0.5334326 ]
 [0.4665621  0.5334379 ]
 [0.466611   0.53338903]
 [0.46656346 0.5334366 ]
 [0.46655637 0.5334436 ]
 [0.4665794  0.5334206 ]
 [0.46656504 0.5334349 ]
 [0.46656093 0.533439  ]
 [0.46655807 0.5334419 ]
 [0.4665518  0.5334482 ]
 [0.46656147 0.53343856]
 [0.46656042 0.53343964]
 [0.46655926 0.5334407 ]
 [0.46655166 0.5334483 ]
 [0.46663368 0.5333664 ]
 [0.4665537  0.5334463 ]
 [0.46655992 0.53344   ]
 [0.4665552  0.53344476]
 [0.4665503  0.53344977]
 [0.46670654 0.5332934 ]
 [0.5179611  0.48203883]
 [0.46679047 0.5332095 ]
 [0.46655124 0.5334488 ]
 [0.50740296 0.492597  ]
 [0.4666615  0.53333855]
 [0.5179611  0.48203883]
 [0.46670547 0.53329444]
 [0.4680927  0.53190726]
 [0.46750474 0.5324952 ]
 [0.46657512 0.53342485]

6/6 [==============================] - 0s 1ms/step
[[0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.51111925 0.48888078]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.5255449  0.47445506]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49370837 0.5062917 ]
 [0.49376404 0.50623596]

1/1 [==============================] - 0s 67ms/step
[[0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]
 [0.499985 0.500015]]
Class :  30
12/12 [==============================] - 0s 1ms/step
[[0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 0.50012696]
 [0.49987304 

5/5 [==============================] - 0s 1ms/step
[[0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.500182  0.4998179]
 [0.50

5/5 [==============================] - 0s 2ms/step
[[0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.499941 0.500059]
 [0.

6/6 [==============================] - 0s 2ms/step
[[0.4997295  0.5002704 ]
 [0.4997193  0.5002807 ]
 [0.49970904 0.500291  ]
 [0.49978775 0.5002123 ]
 [0.49971208 0.5002879 ]
 [0.49970785 0.5002922 ]
 [0.49970913 0.50029093]
 [0.4997171  0.5002829 ]
 [0.49970838 0.50029165]
 [0.49997318 0.5000268 ]
 [0.4997086  0.50029147]
 [0.49970838 0.5002916 ]
 [0.49970785 0.5002922 ]
 [0.49973005 0.50026995]
 [0.4997186  0.5002813 ]
 [0.4997122  0.5002878 ]
 [0.4997111  0.5002889 ]
 [0.49972627 0.5002737 ]
 [0.49970973 0.50029033]
 [0.49971133 0.50028867]
 [0.49970654 0.5002935 ]
 [0.49970788 0.5002922 ]
 [0.49970803 0.50029194]
 [0.49970764 0.50029236]
 [0.49971095 0.500289  ]
 [0.49970928 0.5002907 ]
 [0.49970773 0.5002923 ]
 [0.49970976 0.5002903 ]
 [0.4997326  0.5002674 ]
 [0.49970853 0.50029147]
 [0.49965194 0.50034803]
 [0.49970847 0.5002915 ]
 [0.4997081  0.50029194]
 [0.49970573 0.5002942 ]
 [0.4997125  0.5002875 ]
 [0.49972704 0.5002729 ]
 [0.49970978 0.5002903 ]
 [0.49971205 0.500288  ]

10/10 [==============================] - 0s 1ms/step
[[0.49554956 0.5044505 ]
 [0.49556026 0.50443965]
 [0.49554637 0.5044537 ]
 [0.4955459  0.50445414]
 [0.4955466  0.5044534 ]
 [0.49557304 0.504427  ]
 [0.49554896 0.504451  ]
 [0.49562767 0.5043723 ]
 [0.49561498 0.5043851 ]
 [0.4955458  0.50445426]
 [0.49554694 0.50445294]
 [0.4956196  0.50438035]
 [0.49554533 0.5044547 ]
 [0.49558103 0.5044191 ]
 [0.4955466  0.5044534 ]
 [0.49555576 0.50444424]
 [0.49554554 0.5044545 ]
 [0.49557328 0.5044268 ]
 [0.49589124 0.5041088 ]
 [0.4955534  0.5044465 ]
 [0.49555138 0.5044486 ]
 [0.50005424 0.49994576]
 [0.4955466  0.5044534 ]
 [0.49554718 0.50445276]
 [0.4955454  0.5044546 ]
 [0.497636   0.50236404]
 [0.4955651  0.50443494]
 [0.49559984 0.50440013]
 [0.49554613 0.5044539 ]
 [0.49557763 0.5044224 ]
 [0.4955763  0.50442374]
 [0.49554768 0.5044522 ]
 [0.4955721  0.50442785]
 [0.4955515  0.50444853]
 [0.49559218 0.5044079 ]
 [0.49556023 0.50443965]
 [0.49556288 0.50443715]
 [0.4955471  0.5044529

9/9 [==============================] - 0s 1ms/step
[[0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]
 [0.49999177 0.5000083 ]

7/7 [==============================] - 0s 2ms/step
[[0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]
 [0.5002401  0.49975994]

5/5 [==============================] - 0s 1ms/step
[[0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]
 [0.50009245 0.49990758]

7/7 [==============================] - 0s 2ms/step
[[0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]
 [0.5000906  0.49990934]

8/8 [==============================] - 0s 1ms/step
[[0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]
 [0.50030863 0.49969134]

7/7 [==============================] - 0s 2ms/step
[[0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]
 [0.49999982 0.5000002 ]

9/9 [==============================] - 0s 2ms/step
[[0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]
 [0.49992567 0.5000743 ]

6/6 [==============================] - 0s 2ms/step
[[0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]
 [0.5000107  0.49998933]

6/6 [==============================] - 0s 1ms/step
[[0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.50371164 0.49628836]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]
 [0.49867886 0.5013211 ]

9/9 [==============================] - 0s 1ms/step
[[0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]
 [0.4999049  0.50009507]

7/7 [==============================] - 0s 1ms/step
[[0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]
 [0.49970773 0.50029224]

4/4 [==============================] - 0s 2ms/step
[[0.5000568  0.49994326]
 [0.5000555  0.49994454]
 [0.50005674 0.4999433 ]
 [0.50005674 0.49994326]
 [0.50005674 0.49994323]
 [0.50005674 0.49994326]
 [0.5000567  0.49994335]
 [0.5000567  0.49994332]
 [0.50005674 0.4999433 ]
 [0.500056   0.49994394]
 [0.5000568  0.49994323]
 [0.50005674 0.49994326]
 [0.50005674 0.49994323]
 [0.5000568  0.49994323]
 [0.5000578  0.49994224]
 [0.50005674 0.49994332]
 [0.5000554  0.4999446 ]
 [0.5000568  0.49994326]
 [0.5000568  0.49994326]
 [0.50005484 0.4999452 ]
 [0.50005674 0.49994326]
 [0.5000567  0.49994332]
 [0.5000567  0.49994332]
 [0.50005245 0.49994755]
 [0.50005645 0.49994352]
 [0.5000516  0.4999484 ]
 [0.5000562  0.49994382]
 [0.5000526  0.4999475 ]
 [0.50005674 0.49994326]
 [0.50005454 0.4999455 ]
 [0.5000568  0.4999432 ]
 [0.5000561  0.49994388]
 [0.5000567  0.49994332]
 [0.5000568  0.49994326]
 [0.5000568  0.49994326]
 [0.5000566  0.4999434 ]
 [0.50005656 0.49994344]
 [0.5000567  0.49994338]

6/6 [==============================] - 0s 2ms/step
[[0.47113648 0.52886355]
 [0.47114646 0.5288535 ]
 [0.4711164  0.52888346]
 [0.47109783 0.52890223]
 [0.4711088  0.52889115]
 [0.47109854 0.52890146]
 [0.47125226 0.52874774]
 [0.47118476 0.5288152 ]
 [0.47118038 0.52881956]
 [0.471109   0.5288909 ]
 [0.47127068 0.5287293 ]
 [0.47120294 0.52879703]
 [0.4715945  0.52840555]
 [0.4711037  0.52889633]
 [0.47155765 0.5284423 ]
 [0.47121763 0.5287823 ]
 [0.47299558 0.5270044 ]
 [0.4711019  0.5288981 ]
 [0.47159436 0.5284056 ]
 [0.4714402  0.52855974]
 [0.47111455 0.52888536]
 [0.47109935 0.5289006 ]
 [0.47113308 0.5288668 ]
 [0.47130188 0.52869815]
 [0.47111478 0.52888525]
 [0.4718093  0.5281907 ]
 [0.4711286  0.5288713 ]
 [0.4713417  0.5286582 ]
 [0.47187492 0.52812505]
 [0.4716752  0.52832484]
 [0.4711784  0.5288216 ]
 [0.471109   0.52889097]
 [0.47119918 0.5288008 ]
 [0.47150424 0.52849567]
 [0.47124055 0.52875936]
 [0.47158015 0.52841985]
 [0.47117072 0.5288293 ]
 [0.47110456 0.5288954 ]

9/9 [==============================] - 0s 2ms/step
[[0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]
 [0.49998978 0.5000102 ]

5/5 [==============================] - 0s 1ms/step
[[0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.4826906  0.5173094 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.514909   0.48509106]
 [0.47881988 0.52118015]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.48337382 0.5166261 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.48819667 0.51180327]
 [0.47872558 0.5212744 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.48352885 0.516471  ]
 [0.47869477 0.5213052 ]
 [0.47908938 0.5209107 ]
 [0.47869477 0.5213052 ]
 [0.47913963 0.52086043]
 [0.47869477 0.5213052 ]
 [0.47874588 0.5212541 ]
 [0.47929195 0.52070796]
 [0.47960863 0.5203914 ]
 [0.47869477 0.5213052 ]
 [0.47869477 0.5213052 ]
 [0.4817794  0.5182206 ]

6/6 [==============================] - 0s 2ms/step
[[0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]
 [0.4999682  0.50003177]

5/5 [==============================] - 0s 2ms/step
[[0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]
 [0.50040203 0.49959806]

7/7 [==============================] - 0s 1ms/step
[[0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]
 [0.49987793 0.500122  ]

6/6 [==============================] - 0s 2ms/step
[[0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]
 [0.4999184  0.50008154]

6/6 [==============================] - 0s 1ms/step
[[0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]
 [0.49985263 0.50014734]

6/6 [==============================] - 0s 1ms/step
[[0.49137872 0.5086213 ]
 [0.49141365 0.50858635]
 [0.49137807 0.50862193]
 [0.4916091  0.5083909 ]
 [0.4913935  0.50860655]
 [0.49164954 0.5083505 ]
 [0.491782   0.5082179 ]
 [0.4915418  0.50845826]
 [0.4913939  0.5086061 ]
 [0.49141568 0.50858426]
 [0.49137592 0.5086241 ]
 [0.4913947  0.5086052 ]
 [0.49138346 0.5086165 ]
 [0.49234447 0.5076555 ]
 [0.49193835 0.50806165]
 [0.49144372 0.5085562 ]
 [0.4914999  0.50850004]
 [0.4913765  0.5086235 ]
 [0.4913758  0.50862426]
 [0.49138695 0.50861305]
 [0.49138457 0.5086154 ]
 [0.49143812 0.5085619 ]
 [0.4914008  0.5085993 ]
 [0.49139115 0.50860876]
 [0.49138042 0.5086195 ]
 [0.49138227 0.5086177 ]
 [0.49264032 0.5073598 ]
 [0.49166438 0.5083356 ]
 [0.49145928 0.5085408 ]
 [0.49140564 0.5085943 ]
 [0.49137697 0.50862294]
 [0.491379   0.50862104]
 [0.4915921  0.5084079 ]
 [0.491377   0.50862294]
 [0.49413735 0.50586265]
 [0.49138436 0.5086156 ]
 [0.49153295 0.508467  ]
 [0.4916103  0.5083897 ]

3/3 [==============================] - 0s 2ms/step
[[0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]
 [0.49995297 0.500047  ]

7/7 [==============================] - 0s 1ms/step
[[0.49391168 0.5060883 ]
 [0.49553898 0.5044611 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49637294 0.503627  ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.4939773  0.5060227 ]
 [0.49391168 0.5060883 ]
 [0.49528372 0.5047162 ]
 [0.49391168 0.5060883 ]
 [0.49393165 0.5060684 ]
 [0.49409813 0.5059018 ]
 [0.49412006 0.50588   ]
 [0.49407634 0.50592357]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49414244 0.5058575 ]
 [0.49426708 0.5057329 ]
 [0.49441642 0.5055835 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.4939833  0.5060167 ]
 [0.49391168 0.5060883 ]
 [0.4948462  0.50515383]
 [0.49391168 0.5060883 ]
 [0.49391168 0.5060883 ]
 [0.49431562 0.50568444]
 [0.49391168 0.5060883 ]
 [0.49393082 0.5060692 ]
 [0.49408615 0.5059139 ]

In [284]:
precision

0.5193872315473136

In [ ]:
target_membership

In [ ]:
predicted_membership

In [ ]:
df = pd.DataFrame()
df['target'] = pd.Series(target_membership)
df['predicted'] = pd.Series(predicted_membership)

In [ ]:
df

In [ ]:
df.to_csv('test.csv')

In [ ]:
attack_data = n_attack_data
check_membership = attack_test_data
n_hidden=50
learning_rate=0.01
batch_size=200
epochs=50
model='nn'
l2_ratio=1e-7

In [ ]:
x, y,  classes = attack_data

train_x = x[0]
train_y = y[0]
test_x = x[1]
test_y = y[1]
train_classes = classes[0]
test_classes = classes[1]

#print(tra)


In [ ]:
checkmem_prediction_vals, checkmem_membership_status, checkmem_class_status = check_membership

checkmem_prediction_vals=np.vstack(checkmem_prediction_vals)
checkmem_membership_status=np.array([item for sublist in checkmem_membership_status for item in sublist])
checkmem_class_status=np.array([item for sublist in checkmem_class_status for item in sublist])

train_indices = np.arange(len(train_x))
test_indices = np.arange(len(test_x))
unique_classes = np.unique(train_classes)


predicted_membership, target_membership = [], []

In [ ]:
for c in unique_classes:
    print("Class : ", c)
    c_train_indices = train_indices[train_classes == c]
    c_train_x, c_train_y = train_x[c_train_indices], train_y[c_train_indices]
    c_test_indices = test_indices[test_classes == c]
    c_test_x, c_test_y = test_x[c_test_indices], test_y[c_test_indices]
    c_dataset = (c_train_x, c_train_y, c_test_x, c_test_y)  

    full_cx_data=(c_train_x,c_test_x)
    full_cx_data = np.vstack(full_cx_data)

    full_cy_data=(c_train_y,c_test_y)
    full_cy_data = np.array([item for sublist in full_cy_data for item in sublist])
    full_cy_data = to_categorical(full_cy_data)

    classifier = define_attack_model(2)
    history = classifier.fit(full_cx_data, full_cy_data, epochs=200, batch_size=32, verbose=0)
    #classifier.save('model/attack_model_class{}'.format(c))

    #get predictions on real train and test data
    c_indices = np.where(checkmem_class_status==c)
    predict_y = classifier.predict(checkmem_prediction_vals[c_indices])
    print(predict_y)
    c_pred_y = np.argmax(classifier.predict(checkmem_prediction_vals[c_indices]),axis=1)
    #c_pred_y = np.where(predict_y > 0.5, 1,0)
    #c_pred_y = classifier.predict_classes(checkmem_prediction_vals[c_indices])

    c_target_y = checkmem_membership_status[c_indices]


    target_membership.append(c_target_y)
    predicted_membership.append(c_pred_y)




In [ ]:
c_indices = np.where(checkmem_class_status==c)
predict_y = classifier.predict(checkmem_prediction_vals[c_indices], batch_size=32)
c_pred_y = np.where(predict_y > 0.5, 1,0)
c_target_y = checkmem_membership_status[c_indices]
target_membership.append(c_target_y)
predicted_membership.append(c_pred_y)

In [ ]:
target_membership=np.array([item for sublist in target_membership for item in sublist])
predicted_membership=np.array([item for sublist in predicted_membership for item in sublist])

In [ ]:
prety_print_result (target_membership,predicted_membership)

In [ ]:
np.vstack(predicted_membership).shape

In [ ]:
df = pd.DataFrame()
df['target'] = pd.Series(target_membership)
df['predicted'] = pd.Series(predicted_membership.reshape((len(predicted_membership))))

In [ ]:
df

In [ ]:
predicted_membership